/**
 * Helpers for interacting with the Storm System web service.
 *
 * The Storm API expects an XML document containing a <ciclone>...</ciclone>
 * pedido, which is exactly the output of `gerarXmlRetornoCiclone`.
 *
 * The actual endpoint URL, authentication method and any SOAP envelope
 * should be provided by the Storm team.  These values are injected via
 * environment variables so that secrets are not checked into source control.
 */

const STORM_ENDPOINT = import.meta.env.VITE_STORM_ENDPOINT as string | undefined;
const STORM_API_KEY = import.meta.env.VITE_STORM_API_KEY as string | undefined;

if (!STORM_ENDPOINT) {
  console.warn('VITE_STORM_ENDPOINT is not defined.');
}

/**
 * Sends an XML payload to the Storm system as a "pedido".
 *
 * @param xml - The raw XML string generated by `gerarXmlRetornoCiclone`.
 * @returns The response body as text.
 * @throws Error when the request fails (non‑2xx status).
 */
export async function enviarXmlCiclonePedido(xml: string): Promise<string> {
  if (!STORM_ENDPOINT) {
    throw new Error('Storm endpoint is not configured (VITE_STORM_ENDPOINT).');
  }

  const headers: Record<string, string> = {
    'Content-Type': 'application/xml',
  };

  // optionally send an API key or token if configured
  if (STORM_API_KEY) {
    headers['Authorization'] = `Bearer ${STORM_API_KEY}`;
  }

  const res = await fetch(STORM_ENDPOINT, {
    method: 'POST',
    headers,
    body: xml,
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Storm API error ${res.status}: ${text}`);
  }

  return res.text();
}
