// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evsneoercdzzwxmhuxid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2c25lb2VyY2R6end4bWh1eGlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzMTg5MTQsImV4cCI6MjA3OTg5NDkxNH0.NM0TPX0AuaS_q-9JnzK1eVhZfO4mzNswWu5CPlUvYoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});